version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=achatdb
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: bilelgasmi/achatpipeline
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone