version: '3.3'
  services:
    app:
      image: mohamedghf/devopsprojet
      container_name: achat
      depends_on:
        - mysqldb
      env_file:
        - ./.env
      ports:
        - 8089:8089
      environment:
        SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
              "spring.datasource.username" : "$MYSQLDB_USER",
              "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
      restart: on-failure
    mysqldb:
      image: mysql
      container_name: mysqldb
      environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
      restart: unless-stopped

  volumes:
    db: